Spring:
  main:
    allow-bean-definition-overriding: true
file-storage:
  root: testUploads
  timesheet: ${file-storage.root}/timesheets
  evaluation: ${file-storage.root}/evaluations
default:
  password: DeFaUlTpAsS123
Logging:
  level:
    com.example: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
