spring:
  Datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: User
    password: 4y7sV96vA9wv46VR
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
     ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: application-dev.yml

Logging:
  level:
    com.example: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
initial-data-loader: true